[username]
style_user = "yellow bold"
style_root = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 100
truncate_to_repo = false

[character]
format = "[âš¡ï¸](bold yellow)"

[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[aws]
disabled = true

[time]
disabled = false
format = '[ğŸ•™$time]($style) '
time_format = "%T"
